twitter: "https://twitter.com/_ericthayer/"
github: "https://github.com/ericthayer/"
linkedin: "https://www.linkedin.com/ethayerdesign/"
dribbble: "https://dribbble.com/ethayer/"
codepen: "https://codepen.io/ericthayer/"
