email: "mailto:ethayer.design@gmail.com"
linkedin: "https://www.linkedin.com/ethayerdesign/"
dribbble: "https://dribbble.com/ethayer/"
github: "https://github.com/ericthayer/"
codepen: "https://codepen.io/ericthayer/"
