baseURL = "/"
languageCode = "en-us"
title = "Eric Thayer is a UI/UX Designer and Front-end Developer from Denver Colorado"
disableHugoGeneratorInject = true

# Novela settings
theme = "blog"

paginate = 6

[social]
email = "mailto:ethayer.design@gmail.com"
github = "https://github.com/forestryio/novela-hugo-starter"
linkedin = "https://www.linkedin.com/company/forestry.io"
codepen = "https://codepen.io/ericthayer/"
dribbble = "https://dribbble.com/ethayer/"

[taxonomies]
author = "authors"

