baseURL = "/"
languageCode = "en-us"
title = "Eric Thayer is a UI/UX Designer and Front-end Developer from Denver Colorado"
disableHugoGeneratorInject = true

theme = "blog"
paginate = 6

[params]
  versionTag = "v6"
  devCredits = "<span>made with</span> <a class='mx-sm' href='#0'>Hugo</a> <span>&amp;<span> <a class='ml-0' href='#0'>Netlify</a>"

[social]
  email = "mailto:ethayer.design@gmail.com"
  linkedin = "//linkedin.com/in/ethayerdesign/"
  codepen = "//codepen.io/ericthayer/"
  github = "//github.com/ericthayer/"
  dribbble = "//dribbble.com/ethayer/"

[taxonomies]
  author = "authors"

