baseURL = "/"
languageCode = "en-us"
title = "Eric Thayer is a Web Designer and Front-end Developer from Denver Colorado"
disableHugoGeneratorInject = true
disableLiveReload = true
assetDir = "static"

[params]
  author = "Eric Thayer"
  description = "I'm a freelance consultant with a passion for building design systems and inclusive components with other like-minded people."

## [[menu.main]]
  ## name = "About"
  ## url = "/#about"
  ## weight = 1
  
## [[menu.main]]
 ##  name = "Work"
  ## url = "/#work"
  ## weight = 2
  
## [[menu.main]]
  ## name = "Contact"
  ## url = "/contact"
  ## weight = 4

[[menu.main]]
  name = "Hire"
  url = "/hire-me"
  weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
